ALTER TABLE account ADD OAUTH_TYPE INT DEFAULT 0 NOT NULL;
ALTER TABLE account ADD OAUTH_ID VARCHAR(90) NULL;
ALTER TABLE account MODIFY PASSWORD VARCHAR(200) NOT NULL;
DROP INDEX EMAIL_UNIQUE ON account;

ALTER TABLE lf.account ADD CONSTRAINT account_EMAIL_OAUTH_ID_pk UNIQUE (EMAIL, OAUTH_ID);