ALTER TABLE `account` DROP FOREIGN KEY `FK_ACCOUNT_DETAIL`;
ALTER TABLE `account` DROP INDEX `FK_ACCOUNT_DETAIL_idx` ;

ALTER TABLE `contact` DROP FOREIGN KEY `FK_CONTACT_ACCOUTN_DETAIL`;
ALTER TABLE `contact` DROP INDEX `FK_CONTACT_ACCOUNT_DETAIL_idx` ;

ALTER TABLE `post` DROP FOREIGN KEY `FK_POST_ACCOUNT`, DROP FOREIGN KEY `FK_POST_TYPE`;
ALTER TABLE `post` DROP INDEX `FK_POST_TYPE_idx` , DROP INDEX `FK_POST_ACCOUNT_idx` ;

ALTER TABLE `post_hashtag` DROP FOREIGN KEY `FK_POSTHASHTAG_POST`, DROP FOREIGN KEY `FK_POSTHASHTAG_HASHTAG`;
ALTER TABLE `post_hashtag` DROP INDEX `FK_POSTHASHTAG_POST_idx` , DROP INDEX `FK_POSTHASHTAG_HASHTAG_idx` ;



ALTER TABLE `account` CHANGE COLUMN `ID` `ID` VARCHAR(36) NOT NULL,
                      CHANGE COLUMN `DETAILS_ID` `DETAILS_ID` VARCHAR(36) NOT NULL ;

ALTER TABLE `post_type` CHANGE COLUMN `ID` `ID` VARCHAR(36) NOT NULL ;

ALTER TABLE `hashtag` CHANGE COLUMN `ID` `ID` VARCHAR(36) NOT NULL ;

ALTER TABLE `post_hashtag` CHANGE COLUMN `ID` `ID` VARCHAR(36) NOT NULL,
                           CHANGE COLUMN `ID_POST` `ID_POST` VARCHAR(36) NOT NULL ,
                           CHANGE COLUMN `ID_HASHTAG` `ID_HASHTAG` VARCHAR(36) NOT NULL ;

ALTER TABLE `account_detail` CHANGE COLUMN `ID` `ID` VARCHAR(36) NOT NULL ;

ALTER TABLE `contact` CHANGE COLUMN `ID` `ID` VARCHAR(36) NOT NULL,
                      CHANGE COLUMN `DETAILS_ID` `DETAILS_ID` VARCHAR(36) NOT NULL ;

ALTER TABLE `post` CHANGE COLUMN `ID` `ID` VARCHAR(36) NOT NULL,
                   CHANGE COLUMN `ACCOUNT_ID` `ACCOUNT_ID` VARCHAR(36) NOT NULL ,
                   CHANGE COLUMN `POST_TYPE_ID` `POST_TYPE_ID` VARCHAR(36) NOT NULL ;



ALTER TABLE `account`
ADD CONSTRAINT `FK_ACCOUNT_DETAIL`
FOREIGN KEY (`DETAILS_ID`)
REFERENCES `account_detail` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;


ALTER TABLE `post`
ADD CONSTRAINT `FK_POST_TYPE`
FOREIGN KEY (`POST_TYPE_ID`)
REFERENCES `post_type` (`id`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT `FK_POST_ACCOUNT`
FOREIGN KEY (`ACCOUNT_ID`)
REFERENCES `account` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;


ALTER TABLE `post_hashtag`
ADD CONSTRAINT `FK_POSTHASHTAG_HASHTAG`
FOREIGN KEY (`ID_HASHTAG`)
REFERENCES `hashtag` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT `FK_POSTHASHTAG_POST`
FOREIGN KEY (`ID_POST`)
REFERENCES `post` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;


ALTER TABLE `contact`
ADD CONSTRAINT `FK_CONTACT_ACCOUNT`
FOREIGN KEY (`DETAILS_ID`)
REFERENCES `account` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;