
ALTER TABLE `contact`
DROP FOREIGN KEY `FK_CONTACT_ACCOUNT`;

ALTER TABLE `contact`
CHANGE COLUMN `DETAILS_ID` `POST_ID` VARCHAR(36) NOT NULL ;

ALTER TABLE `contact`
ADD CONSTRAINT `FK_CONTACTS_POST`
  FOREIGN KEY (`POST_ID`)
  REFERENCES `post` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

